# Generated by Django 2.2.6 on 2019-10-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191013_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='last_visit',
            field=models.DateTimeField(null=True, default=None),
            preserve_default=False,
        ),
    ]
