# Generated by Django 2.2.6 on 2019-10-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191013_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteActivity',
        ),
    ]
