# Generated by Django 2.2.6 on 2019-10-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0006_delete_siteactivity")]

    operations = [
        migrations.AlterField(
            model_name="gist",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        )
    ]
