# Generated by Django 2.2.6 on 2019-10-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0007_auto_20191013_2112")]

    operations = [
        migrations.AlterField(
            model_name="gist",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        )
    ]
