# Generated by Django 2.2.6 on 2019-10-14 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GithubUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("username", models.CharField(max_length=100)),
                ("last_visit", models.DateTimeField(null=True)),
            ],
            options={"ordering": ["created"]},
        ),
        migrations.CreateModel(
            name="Gist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("gist_id", models.CharField(max_length=300, unique=True)),
                ("created", models.DateTimeField()),
                ("updated", models.DateTimeField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("comments", models.IntegerField()),
                ("comments_url", models.URLField()),
                (
                    "github_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.GithubUser"
                    ),
                ),
            ],
            options={"ordering": ["created"]},
        ),
    ]
