# Generated by Django 2.2.6 on 2019-10-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="siteactivity", name="id"),
        migrations.AlterField(
            model_name="siteactivity",
            name="last_visit",
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
